# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_cab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='source_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='source_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
