# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_cab', '0003_auto_20160330_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
