# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_cab', '0004_auto_20160331_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='travel_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='uber_arrival_time',
            field=models.IntegerField(null=True),
        ),
    ]
