# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_cab', '0005_auto_20160331_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
