# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_cab', '0006_schedules_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
